src/Mrtn.Marvin21.Ui.Mvc/Controllers/Result/ResultController.cs
using System;
using System.Collections.Generic;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using Mrtn.Marvin21.Bl.Interface.Result;
using Mrtn.Marvin21.Bl.Services.Result;
using Mrtn.Marvin21.Ui.Mvc._infrastructure;

namespace Mrtn.Marvin21.Ui.Mvc.Controllers.Result
{
    public class ResultController : Controller
    {
        readonly IResultService _resultService = new ResultService();


        #region meni, rezultati za na ekran

        //**********************************************
        //****   meni, rezultati za na ekran
        //**********************************************

        /// <summary>
        /// Osnovni seznam rezultatov
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            ViewBag.Days = ApplicationSettings.Days();
            ViewBag.Days = 3;
            return View();
        }

        /// <summary>
        /// Rezultati rodov
        /// </summary>
        /// <returns></returns>
        public ActionResult Packs()
        {
            var model = _resultService.PackResults();
            return View(model);
        }
        /// <summary>
        /// Rezultati rodov
        /// </summary>
        /// <returns></returns>
        public ActionResult PacksPrint()
        {
            var model = _resultService.PackResults();
            ViewBag.Print = true;
            return View("Packs", model);
        }


        /// <summary>
        /// Rezultati ekip po dnevih, za na ekran
        /// </summary>
        /// <param name="day"></param>
        /// <returns></returns>
        public ActionResult TeamsByDay(int day)
        {
            var model = _resultService.TeamsByDayResult(day);
            return View("_ProjectionByDay", model);
        }


        #region Neki ekranski izpisi za GSJ, vsi so enaki ...
        /// <summary>
        /// nekaj za GSJ
        /// </summary>
        /// <returns></returns>
        public ActionResult Teams()
        {
            var model = _resultService.TeamResults();
            return View(model);
        }
        /// <summary>
        /// nekaj za GSJ
        /// </summary>
        /// <returns></returns>
        public ActionResult TeamsPp()
        {
            var model = _resultService.TeamPpResults();
            return View("Teams", model);
        }
        /// <summary>
        /// nekaj za GSJ
        /// </summary>
        /// <returns></returns>
        public ActionResult TeamsTopo()
        {
            var model = _resultService.TeamTopoResults();
            return View("Teams", model);
        }
        /// <summary>
        /// nekaj za GSJ
        /// </summary>
        /// <returns></returns>
        public ActionResult TeamsTt()
        {
            var model = _resultService.TeamTtResults();
            return View("Teams", model);
        }

        #endregion

        #endregion

        #region Projekcija za GSJ - projection
        //**********************************************
        //****   Projekcija za GSJ - projection
        //**********************************************

        /// <summary>
        /// Osnovna akcija za projekcijo GSJ
        /// </summary>
        /// <returns></returns>
        public ActionResult Projection()
        {
            return View();
        }
        public ActionResult ProjectionStarWars()
        {
            return View();
        }



        /// <summary>
        /// servis, ki dejansko vrne HTML z rezultati za GSJ
        /// </summary>
        /// <returns></returns>
        public ActionResult ReloadResults()
        {
            // osnovni rezultati
            var model = _resultService.TeamResults();

            // rezultati po rodovih
            var packResults = _resultService.PackResults();
            ViewBag.PackResualt = packResults;

            return PartialView(model);
        }
        #endregion

        #region Projekcija za ROT po dnevih - projection
        //**********************************************
        //****   Projekcija za ROT po dnevih - projection
        //**********************************************

        /// <summary>
        /// Osnovna akcija za projekcijo GSJ
        /// </summary>
        /// <returns></returns>
        public ActionResult ProjectionByDay(int day)
        {
            ViewBag.Day = day;
            return View();
        }

        /// <summary>
        /// servis, ki dejansko vrne HTML z rezultati za ROT
        /// </summary>
        /// <returns></returns>
        public ActionResult ReloadProjectionByDay(int day)
        {
            // osnovni rezultati
            var model = _resultService.TeamsByDayResult(day);

            // rezultati po rodovih
            var packResults = _resultService.PackResults();
            ViewBag.PackResult = packResults;
            ViewBag.HideTeamNames = true;
            ViewBag.TimeGenerated = DateTime.Now.ToString("H:mm:ss");

            return PartialView("_ProjectionByDay", model);
        }
        #endregion


        public ActionResult TeamsByDayJson()
        {
            var model = _resultService.TeamResults();
            var result = new Dictionary<string, object>();
            var categoryCounter = 1;
            // čez vse kategorije:
            foreach (var category in model.Categories)
            {
                var resultsForCategory = new Dictionary<string, object>();

                // izdelaj glavo
                var resultsHead = new List<string>();
                resultsHead.Add("#");
                resultsHead.Add("Topo");
                resultsHead.Add("Vris");
                resultsHead.Add("SEM");
                resultsHead.Add("PP");
                resultsHead.Add("KT");
                resultsHead.Add("Čas");
                resultsHead.Add("HE");
                resultsHead.Add("TT");
                resultsHead.Add("Sum");
                resultsHead.Add("Ime ekipe");
                var resultForTeamHead = new Dictionary<string, string[]>
                    {
                        { "title", resultsHead.ToArray() }
                    };

                resultsForCategory.Add("0", resultForTeamHead);

                // Čez vse ekipe
                var noCnt = -1;
                foreach (var teamResult in category.TeamResults)
                {
                    var results = new List<string>();
                    results.Add(teamResult.Place.ToString());
                    results.Add(teamResult.TopoPoints.ToString());
                    results.Add(teamResult.VrisPoints.ToString());
                    results.Add(teamResult.SemPoints.ToString());
                    results.Add(teamResult.PpPoints.ToString());
                    results.Add(teamResult.TrackPoints.ToString());
                    results.Add(teamResult.TimePoints.ToString());
                    results.Add(teamResult.SpeedTrialPoints.ToString());
                    results.Add(teamResult.TtPoints.ToString());
                    results.Add(teamResult.Points.ToString());
                    results.Add(teamResult.Name.ToString());

                    var resultForTeam = new Dictionary<string, string[]>
                    {
                        { "data", results.ToArray() }
                    };

                    var no = teamResult.No;
                    if (!no.HasValue)
                    {
                        no = noCnt;
                        noCnt--;
                    }

                    resultsForCategory.Add(no.ToString(), resultForTeam);
                }
                result.Add(category.Category.No.ToString(), resultsForCategory);
                categoryCounter++;
            }



            var packModel = _resultService.PackResults();

            var packResults = new Dictionary<string, object>();

            // izdelaj glavo
            var packResultsHead = new List<string>();
            packResultsHead.Add("#");
            packResultsHead.Add("Rod");
            packResultsHead.Add("Sum");
            packResultsHead.Add("Ekipe");
            var packResultHead = new Dictionary<string, string[]>
                    {
                        { "title", packResultsHead.ToArray() }
                    };

            packResults.Add("0", packResultHead);

            // Čez vse rodove
            var pckCnt = 1;
            foreach (var pack in packModel)
            {
                var results = new List<string>();

                results.Add(pack.Place.ToString());
                results.Add(pack.PackNam + " " + pack.PackTown);
                results.Add(pack.Points.ToString());
                results.Add(pack.Teams.Replace("<i>","").Replace("</i>",""));

                var resultForPack = new Dictionary<string, string[]>
                    {
                        { "data", results.ToArray() }
                    };



                packResults.Add(pckCnt.ToString(), resultForPack);
                pckCnt++;
            }


            result.Add(categoryCounter.ToString(), packResults);
            var res = Json(result, JsonRequestBehavior.AllowGet);
            var serializer = new JavaScriptSerializer();     
            var output = serializer.Serialize(res.Data);
            System.IO.File.WriteAllText(HttpRuntime.AppDomainAppPath + @"\results.txt", output); 
            return res;
        }

    }
}

src/Mrtn.Marvin21.Ui.Mvc/Controllers/Run/RunTaskController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Mrtn.Marvin21.Model.Common;
using Mrtn.Marvin21.Bl.Interface.Run;
using Mrtn.Marvin21.Bl.Services.Run;

namespace Mrtn.Marvin21.Ui.Mvc.Controllers.Run
{
    public class RunTaskController : Controller
    {
        readonly IRunTaskService _runTaskService = new RunTaskService();
        //
        // GET: /RunTask/

        public ActionResult Edit(int id)
        {
            var model = _runTaskService.GetEditModels(id);
            return View(model);
        }

        public ActionResult TrySaveCell(int id, int taskId, string firstEntry, string secondEntry)
        {
            var response = _runTaskService.TrySaveCell(id, taskId, firstEntry, secondEntry);
            return Json(response, JsonRequestBehavior.AllowGet);
        }
        public JsonResult Lock(int id)
        {
            var response = _runTaskService.Lock(id);
            return Json(response, JsonRequestBehavior.AllowGet);
        }
        public JsonResult Unlock(int id)
        {
            var response = _runTaskService.Unlock(id);
            return Json(response, JsonRequestBehavior.AllowGet);
        }
        public JsonResult LockCategory(int taskId , int  categoryId)
        {
            var response = _runTaskService.LockCategory(taskId, categoryId);
            return Json(response, JsonRequestBehavior.AllowGet);
        }
        public JsonResult UnlockCategory(int taskId, int categoryId)
        {
            var response = _runTaskService.UnlockCategory(taskId, categoryId);
            return Json(response, JsonRequestBehavior.AllowGet);
        }
    }
}

src/Mrtn.Marvin21.Ui.Mvc/Controllers/Run/RunTrackController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Mrtn.Marvin21.Model.Common;
using Mrtn.Marvin21.Model.Run;
using Mrtn.Marvin21.Bl.Interface.Run;
using Mrtn.Marvin21.Bl.Services.Run;
using Mrtn.Marvin21.Model.RunTrack.Support;

namespace Mrtn.Marvin21.Ui.Mvc.Controllers.Run
{
    public class RunTrackController : Controller
    {
        private readonly IRunTrackService _runTrackService = new RunTrackService();

        //
        // GET: /RunTrack/

        public ActionResult View(int id)
        {
            //id = runTrackId
            var model = _runTrackService.Get(id);
            return View("Index", model);
        }
        public ActionResult Add(int teamId, int day)
        {
            var model = _runTrackService.Add(teamId, day);
            return Redirect(Url.Action("View", new { id = model.Id }));
            //return Redirect(RunTrackController("View", new { id = model.Id }));
        }
        public ActionResult AddAll(int day)
        {
            var model = _runTrackService.AddAll(day);
            return Redirect(Url.Action("Index", "DashBoard", new { day = day }));
        }


        public JsonResult Lock(int id)
        {
            var response = _runTrackService.Lock(id);
            return Json(response, JsonRequestBehavior.AllowGet);
        }
        public JsonResult Unlock(int id)
        {
            var response = _runTrackService.Unlock(id);
            return Json(response, JsonRequestBehavior.AllowGet);
        }

        public JsonResult DeleteResults(int id)
        {
            var response = _runTrackService.DeleteResults(id);
            return Json(response, JsonRequestBehavior.AllowGet);
        }


        [HttpGet]
        public ActionResult EditRejectManualy(int id)
        {
            RejectedManualyEditModel model;
            try
            {
                model = _runTrackService.EditRejectManualy(id);
            }
            catch (Exception e)
            {
                return Content(e.Message);
            }
            return PartialView("_EditRejectManualy", model);

        }
        [HttpPost]
        public JsonResult EditRejectManualy(RejectedManualyEditModel model)
        {
            var response = _runTrackService.Save(model);
            return Json(response, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult EditConfirmManualy(int id)
        {
            ConfirmManualyEditModel model;
            try
            {
                model = _runTrackService.EditConfirmManualy(id);
            }
            catch (Exception e)
            {
                return Content(e.Message);
            }
            return PartialView("_EditConfirmManualy", model);
        }
        [HttpPost]
        public JsonResult EditConfirmManualy(ConfirmManualyEditModel model)
        {
            var response = _runTrackService.Save(model);
            return Json(response, JsonRequestBehavior.AllowGet);
        }


        [HttpGet]
        public ActionResult SetPredictedStartTime(int id)
        {
            PredictedStartTimeEditModel model;
            try
            {
                model = _runTrackService.GetModelForPredictedStartTime(id);
            }
            catch (Exception e)
            {
                return Content(e.Message);
            }
            return PartialView("_SetPredictedStartTime", model);
        }
        [HttpPost]
        public JsonResult SetPredictedStartTime(PredictedStartTimeEditModel model)
        {
            var response = _runTrackService.Save(model);
            return Json(response, JsonRequestBehavior.AllowGet);
        }


        [HttpGet]
        public ActionResult ManualDeparture(int id)
        {





            ManualDepartureEditModel model;
            try
            {
                model = _runTrackService.ManualDeparture(id);
            }
            catch (Exception e)
            {
                return Content(e.Message);
            }
            return PartialView("_ManualDeparture", model);


        }
        [HttpPost]
        public JsonResult ManualDeparture(ManualDepartureEditModel model)
        {
            var response = _runTrackService.Save(model);
            return Json(response, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult ManualArrival(int id)
        {



            ManualArrivalEditModel model;
            try
            {
                model = _runTrackService.ManualArrival(id);
            }
            catch (Exception e)
            {
                return Content(e.Message);
            }
            return PartialView("_ManualArrival", model);



        }
        [HttpPost]
        public JsonResult ManualArrival(ManualArrivalEditModel model)
        {
            var response = _runTrackService.Save(model);
            return Json(response, JsonRequestBehavior.AllowGet);
        }

    }
}

src/Mrtn.Marvin21.Ui.Mvc/Views/DashBoard/CheckForSiReads.cshtml
@model Mrtn.Marvin21.Model.Common.SiReadReportResponse
<h2>Uvoz čipov za dan @Model.Day</h2>
<div>
    @if (!Model.Success)
    {
        <div class="error">@Model.ErrorMessage </div>
    }
    <h2>Uvoz iz sportident baze</h2>
    @if (!Model.ImportFromSiRead.Success)
    {
        <div class="error">@Model.ImportFromSiRead.ErrorMessage </div>
    }
    <table>
        <tr>
            <th>Čip</th>
            <th>Novo?</th>
            <th>Sporočilo</th>
        </tr>
        @foreach (var line in Model.ImportFromSiRead.Lines)
        {<tr>
            <td>@line.SiChip</td>
            <td>@(line.IsNew ? "Novo" : "-")</td>
            <td>@line.Text</td>
        </tr>
        }
    </table>
    <h2>Procesiranje...</h2>
    <table>
        <tr>
            <th>Čip</th>
            <th>Status</th>
            <th>Ekipa</th>
            <th>Sporočilo</th>
        </tr>
        @foreach (var line in Model.RunTrackProcessReport.Lines)
        {<tr>
            <td>@line.SiChip</td>
            <td>@line.Status</td>
            <td>@line.Team</td>
            <td>@line.Text</td>
        </tr>
        }
    </table>

</div>

src/Mrtn.Marvin21.Ui.Mvc/Views/DashBoard/IndexDashboard.cshtml
@using System.Web.UI.WebControls
@model Mrtn.Marvin21.Model.Run.DashBoardViewModel
@{
    if (ViewBag.Print != null && ViewBag.Print)
    {
        Layout = "~/Views/Shared/_Print.cshtml";
    }
}


@if (ViewBag.Print == null || ViewBag.Print == false)
{
    // Gumbi na vrhu, če ni za printanje
    <div style="float: right; height: 30px;">
        izberi dan: 
        @Html.Partial("../_components/DayPicker")
        <input type="checkbox" value="true" name="showInactive" id="inactiveSelect"/>neaktivni
    </div>
    <div style="float: right; height: 30px; margin-right: 50px;">
        <a href="@Url.Action("Packs", "Result")" class="linkAsButton" target="_blank">Rezultati
            rodovi</a>

        <a href="@Url.Action("CheckForSiReads")" class="linkAsButton" id="CheckForSiReadsButton">Preberi
            nove čipe</a>
        
        <a href="@Url.Action("RecalculateTeams")" class="linkAsButton" id="RecalculateTeamsButton" title="Nova funkcija, da se preračunajo točke in procenti">Preračunaj in osveži</a>
    </div>
    <div style="float: right; height: 30px; margin-right: 50px;">

        @for (var i = 1; i < ViewBag.Days + 1; i++)
        {
            <a href="@Url.Action("Print", new { day = i })" class="linkAsButton" target="_blank">Print dan @i</a>
        }

    </div>
    <div style="float: right; height: 30px; margin-right: 50px;">
        <a href="@Url.Action("DeleteUnusedSiReads")" class="linkAsButton ajaxLink" id="">Pobriši neznana branja</a>
    </div>
    <h2>Nadzorna plošča
    </h2>
}
else
{
    // Čas izpisa, če je za print
    <div style="float: right; height: 30px;">
        Čas izpisa:@ViewBag.TimePrint
    </div>
    <h2>Rezultati za dan @ViewBag.CurrentDay
    </h2>
}
<table class="standard-table" style="border-bottom: solid 2px #5c87b2;">
    <tr>
        <th colspan="2">
            Ekipa
        </th>
        @foreach (var header in Model.Headers)
        {
            if (header.IsTrack)
            {
                <th colspan="5">
                    @header.Name
                </th>
            }
            else
            {
                <th>
                    @header.Name
                    <br />
                    <span style="font-weight: normal">@header.Location</span>
                </th>
            }

        }
        <th rowspan="2">
            Skupaj
        </th>
        <th rowspan="2">
            Mesto
        </th>
        <th rowspan="2">
            %
        </th>
        <th rowspan="2">
            *
        </th>
    </tr>
    <tr>
        <th>No
        </th>
        <th>Ime
        </th>
        @foreach (var header in Model.Headers)
        {
            if (header.IsTrack)
            {
            <th>KT-jev:
            </th>
            <th>Točke:
            </th>
            <th>Čas:
            </th>
            <th>HE:
            </th>
                <th>
                    <a href="@Url.Action("AddAll", "RunTrack", new { day = ViewBag.CurrentDay })" class="linkAsButton" >Dodaj vse</a>
                </th>
            }
            else
            {
            <th>
                @if (!header.Sum)
                {
                    <a href="@Url.Action("Edit", "RunTask", new { id = header.TaskId })" class="linkAsButton" >Uredi</a>
                }
            </th>
            }
        }
    </tr>
    @{var previousCategoryId = 0;}
    @foreach (var row in Model.Rows)
    {
        // izpis posamezne vrstice

        if (row.Team.CategoryId != previousCategoryId)
        {
            // izpis imena kategorija 
            previousCategoryId = row.Team.CategoryId;
        <tr>
            <td colspan="19" style="border-top: solid 2px #5c87b2;">
                <b>
                    @row.Team.CategoryName</b>
            </td>
        </tr>
        }
        
<tr>
    <td>
        @row.Team.No
</td>
<td>
    @row.Team.Name (@row.Team.PackAbbr)
</td>
@foreach (var cell in row.Cells)
{
    var cls = "";

    if (cell.HasNoEntry)
    {
        cls = cls + " greyCell";
    }
    if (cell.NoResultYet)
    {
        cls = cls + " redCell";
    }
    if (cell.Locked)
    {
        cls = cls + " greenCell";
    }
    if (cell.IsTrack)
    {

        <td class="@cls">
            @cell.CheckpointsFound
    </td>
    <td class="@cls">
        @cell.PointsForCheckpoints
</td>
<td class="@cls">
    @cell.PointsForTime
</td>
<td class="@cls">
    @cell.SpeedTrialPoints
</td>
<td class="@cls">
    @if (!cell.Locked)
    {
        if (cell.RunTrackId > 0)
        {
            <a href="@Url.Action("View", "RunTrack", new { id = cell.RunTrackId })" class="linkAsButton">
                Uredi
                (@(cell.StartPredicted))
            </a>
        }
        else
        {
            <a href="@Url.Action("Add", "RunTrack", new { teamId = cell.TeamId, day = cell.Day })" class="linkAsButton">Dodaj</a>
        }
    }
    else
    {
        <a href="@Url.Action("View", "RunTrack", new { id = cell.RunTrackId })" class="linkAsButton">Poglej</a>
    }
</td>
}
else
{
<td class="@cls">
    @if (!cell.HasNoEntry && !cell.NoResultYet)
    {
        @cell.TaskPoints
    }
</td>
}
}
@{var notValid = (!row.Team.InCompetition || !row.Team.Active);
}
<td>
    <b>@row.Team.Points</b>
</td>
<td class="@(notValid ? "warning" : "")">
    <b>@row.Team.Place</b>
</td>
<td>
    <b>@row.Team.PercentString</b>
</td>
<td class="@(notValid ? "warning" : "")">
    <b>
        @if (!row.Team.InCompetition)
        {
            <span title='Izven konkurence'>IK</span>
        }
        @if (!row.Team.Active)
        {
            <span title='Neaktivna (diskvalificirana) ekipa'>NA</span>
        }
    </b>
</td>
</tr>
    }
</table>
<script type="text/javascript">
    var Reload = function () {
        var urlparts = window.location.href.split('?');
        var day = $("option:selected", "#daySelect").first().val();
        window.location.href = urlparts[0] + "?day=" + day;
    }

    $(document).ready(function () {

        $("a.ajaxLink").click({ success: Reload }, callAjaxLink);

        $("#daySelect").change(Reload);

        $("#RecalculateTeamsButton").click(function() {
            var aHref = $(this).attr('href');

            $.ajax(aHref)
                    .done(function (data) {
                        Reload();
                    })
                ;
            return false;

        });

        

        $("#CheckForSiReadsButton").click(function () {

            var aHref = $(this).attr('href');
            var urlparts = aHref.split('?');
            var day = $("option:selected", "#daySelect").first().val();
            aHref = urlparts[0] + "?day=" + day;

            //$.ajax(aHref)
            //  .done(function (data) {
            //      alert(data);
            //        Reload();
            //    })
            //;


            var dialog = $('<div />');
            // load remote content
            $.get(aHref,
                function (data) {
                    dialog.html(data);
                    dialog.dialog({
                        height: 700,
                        width: 900,
                        modal: true,
                        buttons: {
                            "Zapri": function () {
                                $(this).dialog("close");
                            }
                        },
                        close: function (event, ui) {
                            $(this).remove();
                        },
                        title: "Rezultati uvoza"
                    });
                    //tole je za validacijo
                }
            );




            return false;







        });


    });

</script>