src/Mrtn.Marvin21.Ui.Mvc/Controllers/Support/PrintController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Mrtn.Marvin21.Bl.Interface.Run;
using Mrtn.Marvin21.Bl.Interface.Tracks;
using Mrtn.Marvin21.Bl.Services.Run;
using Mrtn.Marvin21.Bl.Services.Tracks;
using Mrtn.Marvin21.Model.RunTrack;
using Mrtn.Marvin21.Model.Tracks;

namespace Mrtn.Marvin21.Ui.Mvc.Controllers.Support
{

    public class PrintController : Controller
    {
        readonly ITrackService _trackService = new TrackService();
        readonly IRunTrackService _runTrackService = new RunTrackService();
        readonly IStationService _stationService = new StationService();
            
        // GET: /Print/

        public ActionResult TrackTable(int id)
        {
            TrackWithCheckpointsViewModel model = _trackService.Get(id);
            return View(model);
        }
        public ActionResult TrackTables(int id)
        {
            ViewModelForTrackTables
                model = _runTrackService.GetModelForTrackTables(id);

            return View(model);
        }

        public ActionResult Station(int id)
        {
            var model=_stationService.GetModelForStation(id);
            return View(model);
        }
    }
}

src/Mrtn.Marvin21.Ui.Mvc/Controllers/TrackController.cs
using System.Web.Mvc;
using Mrtn.Marvin21.Bl.Interface.Tracks;
using Mrtn.Marvin21.Bl.Services.Tracks;
using Mrtn.Marvin21.Model.Tracks;

namespace Mrtn.Marvin21.Ui.Mvc.Controllers
{
    public class TrackController : Controller
    {
        readonly ITrackService _trackService = new TrackService();

        public ActionResult Index(int? id)
        {
            ViewBag.Id = id.GetValueOrDefault();
            return View();
        }


        public ActionResult GetTracks(TrackQueryModel queryModel)
        {
            if (queryModel == null) queryModel = new TrackQueryModel();
            var model = _trackService.GetTracks(queryModel);
            return PartialView("_List", model);
        }

        public ActionResult GetTrack(int id)
        {
            if (id == 0) return Content("Izberi progo");
            var model = _trackService.Get(id);
            return PartialView("_Track", model);
        }

        //[HttpGet]
        //public ActionResult Edit(int? id)
        //{
        //    try
        //    {
        //        var model = _trackService.Edit(id);
        //        return PartialView("_Edit", model);
        //    }
        //    catch (Exception ee)
        //    {
        //        return PartialView("exception", ee);
        //    }
        //}

        //[HttpPost]
        //public JsonResult Edit(TrackEditModel model)
        //{
        //    var response = _trackService.Save(model);
        //    return Json(response, JsonRequestBehavior.AllowGet);
        //}



        public JsonResult RemoveSpeedTrial(int id)
        {
            //id=idTrack
            var response = _trackService.RemoveSpeedTrial(id);
            return Json(response, JsonRequestBehavior.AllowGet);
        }

        public JsonResult SetSpeedTrial(int id)
        {
            //id = idCheckpoint
            var response = _trackService.SetSpeedTrial(id);
            return Json(response, JsonRequestBehavior.AllowGet);
        }

        public JsonResult Lock(int id)
        {
            var response = _trackService.Lock(id);
            return Json(response, JsonRequestBehavior.AllowGet);
        }
        public JsonResult Unlock(int id)
        {
            var response = _trackService.Unlock(id);
            return Json(response, JsonRequestBehavior.AllowGet);
        }

    }
}

src/Mrtn.Marvin21.Ui.Mvc/Controllers/TrackManualController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using Mrtn.Marvin21.Bl.Interface.Teams;
using Mrtn.Marvin21.Bl.Interface.Tracks;
using Mrtn.Marvin21.Bl.Services.Teams;
using Mrtn.Marvin21.Bl.Services.Tracks;
using Mrtn.Marvin21.Model.Common;
using Mrtn.Marvin21.Model.Teams;
using Mrtn.Marvin21.Model.Tracks;
using Mrtn.Marvin21.Ui.Mvc._infrastructure;

namespace Mrtn.Marvin21.Ui.Mvc.Controllers
{
    public class TrackManualController : Controller
    {
        private readonly ITrackService _trackService = new TrackService();
        private readonly ITrackCheckpointService _trackCheckpointService = new TrackCheckpointService();
        private readonly ICategoryService _categoryService = new CategoryService();
        private readonly IStationService _stationService = new StationService();

        public ActionResult Index(int? id)
        {
            ViewBag.Days = ApplicationSettings.Days();
            ViewBag.CurrentDay = ApplicationSettings.GetCurrentDay(Session);
            ViewBag.Id = id ?? 0;
            return View("IndexTrackManual");

        }

        public ActionResult GetTracks()
        {
            var days = new List<int>();
            for (var i = 1; i < ApplicationSettings.Days() + 1; i++)
            {
                if (_stationService.Get(new StationQueryModel() { Day = i }).Count > 0) days.Add(i);
            }
            ViewBag.Days = days;
            ViewBag.Categories = _categoryService.GetAll();
            var model = _trackService.GetTracks(new TrackQueryModel());
            return PartialView("_Tracks", model);

        }
        /// <summary>
        /// vrne posamezen track
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult GetTrack(int id)
        {
            if (id == 0) return Content("Izberi progo");
            var model = _trackService.Get(id);
            return PartialView("_Track", model);
        }

        public JsonResult AddToTrack(int id, int stationId)
        {
            var response = _trackCheckpointService.Add(id, stationId);
            //var response = new SuccessResponse(false, "notimplemented");
            return Json(response, JsonRequestBehavior.AllowGet);

        }


        [HttpGet]
        public ActionResult EditCheckpoint(int id)
        {
            try
            {
                var model = _trackCheckpointService.Edit(id);
                return PartialView("_Edit", model);
            }
            catch (Exception ee)
            {
                return PartialView("exception", ee);
            }
        }

        [HttpPost]
        public JsonResult EditCheckpoint(TrackCheckpointEditModel model)
        {
            TimeSpan t;

            if (!TimeSpan.TryParse("0:" + model.TimeFromPrevious, out t))
                return Json(new SuccessResponse(false, "Preveri format pri času!"), JsonRequestBehavior.AllowGet);


            var response = _trackCheckpointService.Save(model, t.TotalSeconds);
            return Json(response, JsonRequestBehavior.AllowGet);
        }


        [HttpGet]
        public JsonResult AddTrack(int category, int day)
        {
            var response = _trackService.Add(category, day);
            return Json(response, JsonRequestBehavior.AllowGet);
        }
    }
}

src/Mrtn.Marvin21.Ui.Mvc/Views/TrackManual/IndexTrackManual.cshtml
@{
    ViewBag.Title = "Ročni vnos prog";
}
@*<div class="leftDivMenu">

    <select name="day" style="font-size: 12px" id="daySelect">
        @for (var i = 1; i < ViewBag.Days + 1; i++)
        {
            <option value="@i" @(ViewBag.CurrentDay == i ? "selected='selected'" : "")>@i. dan</option>
        }
    </select>
    <a href='@Url.Action("UnlockAll")' class="ajaxLink unlockButton addDayBeforeClick" title="Odkleni vse točke"></a>
    <a href='@Url.Action("LockAll")' class="ajaxLink lockButton addDayBeforeClick" title="Zakleni vse točke"></a>
</div>
<div class="leftDivMenu">
    @( Html.ActionLink("Dodaj točko", "Add", new { day = ViewBag.CurrentDay, type = "kt" }, new
                {
                    @class = "ajaxDialog linkAsButton",
                    data_popup_name = "Dodajanje točke",
                    data_popup_width = 800,
                    data_popup_height = 600
                }))
</div>*@

<h3>@ViewBag.Title</h3>
<div id="tracksDiv">
</div>
<div id="trackDiv"></div>
<style  type="text/css" >
    .selectedTrack {
        background:#ffffcc;
    }
</style>

<script type="text/javascript">
    var trackId = @ViewBag.Id;
    var setBackgroundColorInTrackTable=function() {
        $("#tracksDiv td").removeClass("selectedTrack");
        $("#tracksDiv td[data-id="+trackId+"]").addClass("selectedTrack");
    };

    var refreshTracks = function () {
        $.get('@Url.Action("GetTracks")',
            function (data) {
                $("#tracksDiv").html(data);
                loadTrack(trackId);
            }
        );
    }
    var loadTrack = function (id) {
        $.get('@Url.Action("GetTrack")?id='+id,
            function (data) {
                $("#trackDiv").html(data);
                trackId = id;
                setBackgroundColorInTrackTable();
            }
        );
    }
    var tryLoadTrack=function() {
        var dataId = $(this).data("id");
        if (typeof dataId == "undefined") return true;
        loadTrack(dataId);
        return true;
    }

    $(function () {

        // Handler for .ready() called.
        // console.debug("ready");


        $("div#tracksDiv").delegate("a.ajaxLink", "click", { success: refreshTracks }, callAjaxLink);
        $("div#tracksDiv").delegate("td[data-id]", "click", { success: refreshTracks }, tryLoadTrack);


        $("div#trackDiv").delegate("a.ajaxLink", "click", { success: refreshTracks }, callAjaxLink);
        $("div#trackDiv").delegate("a.ajaxDialog", "click", { success: refreshTracks }, openLinkDialog);
        //$("a.ajaxLink").live('click', { success: refreshTracks }, callAjaxLink);


        $("div#trackDiv")
            .delegate("a.editStationButton", 'click', function () { return false; })
            .delegate("a.editStationButton", 'dblclick', { success: refreshTracks }, openLinkDialog);

        $("div#trackDiv")
            .delegate("a.editPathButton", 'click', function () { return false; })
            .delegate("a.editPathButton", 'dblclick', { success: refreshTracks }, openLinkDialog);


        // handler za odklepanje/zaklepanje
        $("div#trackDiv").delegate("a.lockUnlockButton", 'click', function () {
            var id = $(this).data("id");
            var url = this.href;
            if (!url) return false;
            $.get(url + "/" + id,
                function (data) {
                    if (data.Message && data.Message != "") alert(data.Message);
                    //selectedTrack = id;
                    refreshTracks();
                }
            );
            return false;
        });


        //$("a.ajaxDialog").live('click', { success: refreshCategories }, openLinkDialog);
        //$("#daySelect").change(refreshCategories);

        //$("a.addDayBeforeClick").click(function () {
        //    var t = $(this);
        //    if (typeof t.data("ohref") == "undefined")
        //        t.data("ohref", t.attr("href"));
        //    var day = $("option:selected", "#daySelect").first().val();
        //    $(this).attr("href", t.data("ohref") + '?day=' + day);
        //    return true;
        //});


        refreshTracks();
    });


</script>




src/Mrtn.Marvin21.Ui.Mvc/Views/TrackManual/_Edit.cshtml
@model  Mrtn.Marvin21.Model.Tracks.TrackCheckpointEditModel
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    <fieldset id="packFieldset">
        @Html.HiddenFor(model => model.Id)
        <div class="editor-label">
            @Html.LabelFor(model => model.Points)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.Points, new { @class = "shortTextBox" }) 
            @Html.ValidationMessageFor(model => model.Points)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.TimeFromPrevious)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.TimeFromPrevious, new { @class = "shortTextBox" }) 
            @Html.ValidationMessageFor(model => model.TimeFromPrevious)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.Description, new { rows = 5, cols = 50 })
            @Html.ValidationMessageFor(model => model.Description)
        </div>
    </fieldset>
}

src/Mrtn.Marvin21.Ui.Mvc/Views/TrackManual/_RemainingStationsPartial.cshtml
@model Mrtn.Marvin21.Model.Tracks.TrackWithCheckpointsViewModel
<h3>Preostale točke:
</h3>
<table class="standard-table">
    <tr>
        <th>Ime
        </th>
        <th>Tip točke
        </th>
        <th title="Je skrita (ranjenec)?">S?
        </th>
        <th>Kode
        </th>
        <th>Točke
        </th>
        <th>Proge
        </th>
        <th>Urejanje 
        </th>
    </tr>
    @foreach (var item in Model.RemainingStations)
        {
        <tr>
            <td>
                @item.Name
            </td>
            <td>
                @(item.IsStart ? "Start" : item.IsFinish ? "Cilj" : item.IsAlive ? "Živa KT" : "KT")
            </td>
            <td>
                @(item.IsHidden ? "DA" : "-")
            </td>
            <td>
                @item.SiCodeArrival  @(item.SiCodeDeparture == null || item.SiCodeDeparture.Trim() == ""
                ? ""
                : " -> " + item.SiCodeDeparture)
            </td>
            <td>
                @item.DefaultPoints
            </td>
            <td>
                @item.Tracks
            </td>

            <td>
                @Html.ActionLink("Dodaj", "AddToTrack", new {id=Model.Id, stationId = item.Id }, new
                {
                    @class = "ajaxLink linkAsButton "
                })

            </td>

        </tr>
        }
</table>

src/Mrtn.Marvin21.Ui.Mvc/Views/TrackManual/_Track.cshtml
@model Mrtn.Marvin21.Model.Tracks.TrackWithCheckpointsViewModel

<div style="float: left; width: 70%">
    @Html.Partial("_TrackPartial", Model)
</div>
<div style="float: right; width: 29%; ">
    @Html.Partial("_RemainingStationsPartial", Model)
</div>
<div style="clear: both;"></div>

src/Mrtn.Marvin21.Ui.Mvc/Views/TrackManual/_TrackPartial.cshtml
@model Mrtn.Marvin21.Model.Tracks.TrackWithCheckpointsViewModel
<h3>Proga za kategorijo @Model.CategoryAbbr, dan @Model.Day
</h3>
@*
******************************************
   Zgornja tabela s povzetki
******************************************
*@ 
<table data-day="@Model.Day" class="standard-table" style="border-bottom: solid 2px #5c87b2; white-space: nowrap;">
    <tr style="border-top: solid 2px #5c87b2;">
        <th>Kategorija
        </th>
        <td>
            <h3 style="margin: 0px">@Model.CategoryAbbr (@Model.CategoryNo)</h3>
        </td>
        <th></th>
        <td colspan="3">
            @if (Model.Locked)
            {
                <a class="lockUnlockButton lockButton" href="@Url.Action("Unlock", "Track")" data-id="@Model.Id"
                    title="Odkleni progo"></a>
            }
            else
            {
                <a class="lockUnlockButton unlockButton" href="@Url.Action("Lock", "Track")" data-id="@Model.Id"
                    title="Zakleni progo"></a>
            }
            <a class="mapButton" href="@Url.Action("Index", "MapTrack", new { id = Model.Id })"
               title="Prikaži progo na zemljevidu"></a>
            <a class="linkAsButton " target="_blank"
               href="@(Url.Action("GetMap", "Rendermap"))/@(Model.CategoryAbbr)_d@(Model.Day).png?id=@Model.Id">Zemljevid proge</a>
            <a class="linkAsButton " target="_blank"
               href="@(Url.Action("TrackTable", "Print", new { id = Model.Id }))">Tabela</a>
            <a class="linkAsButton " target="_blank"
               href="@(Url.Action("TrackTables", "Print", new { id = Model.Id }))">Tabele po ekipah</a>
        </td>
    </tr>
    <tr>
        <th>Optimalni čas na progi
        </th>
        <td>
            @Model.OptimalPathTime
        </td>
        <th>Razdalje:
        </th>
        <td>Dolžina poti: &rarr; @Model.CumulativeDistance m
        </td>
        <td>Vzponi: &#8599; @Model.CumulativeUphill m
        </td>
        <td>Spusti: &#8600; @Model.CumulativeDownhill m
        </td>
    </tr>
    <tr>
        <th>Optimalni skupni čas (proga + naloge)
        </th>
        <td>
            @Model.OptimalTime
        </td>
        <th>Število točk (skupaj s startom in ciljem)
        </th>
        <td colspan="3">
            @Model.TrackCheckpointsCount
        </td>
    </tr>
</table>
<br />
@*
******************************************
   Tabela s kontrolnimi točkami
******************************************
*@ 
<table class="standard-table" style="border-bottom: solid 2px #5c87b2; white-space: nowrap;">
    <tr style="border-top: solid 2px #5c87b2;">
        <th>KT
        </th>
        <th colspan="1">Kode
        </th>
        <th colspan="2">Premik
        </th>
        <th colspan="1">Točka
        </th>
        <th colspan='1'>Točke
        </th>
        <th colspan='1'>Prihod
        </th>
        <th colspan='2'>Naloge
        </th>
        <th colspan='1'>Odhod
        </th>
        <th colspan='1'>Umik
        </th>
        <th colspan='1' title="Hitrostna etapa">HE
        </th>
        <th colspan='1'>Čas od prejšnje KT
        </th>
        <th colspan='5'></th>
    </tr>
    @foreach (var checkpoint in Model.TrackCheckpoints)
    {
        var cl = "";
        var cl1 = "";
        if (checkpoint.StationIsStart)
        {
            cl = "startButton";
            cl1 = cl;
        }
        else if (checkpoint.StationIsFinish)
        {
            cl = "finishButton";
            cl1 = cl;
        }
        else
        {
            cl = "ktFlagButton";
            if (checkpoint.StationIsAlive) { cl1 = "aliveButton"; } else { cl1 = "ktButton"; }
        }

        // Priprava niza za izpis kode (31=>62)
        var s = "";
        if (checkpoint.StationIsStart == false && checkpoint.StationIsFinish == false)
        {
            if (!string.IsNullOrEmpty(checkpoint.StationSiCodeArrival)
             || !string.IsNullOrEmpty(checkpoint.StationSiCodeDeparture))
            {
                if (!string.IsNullOrEmpty(checkpoint.StationSiCodeArrival))
                {
                    s = s + checkpoint.StationSiCodeArrival;
                    if (!string.IsNullOrEmpty(checkpoint.StationSiCodeDeparture))
                    {
                        s = s + "&rArr;";
                    }
                }
                if (!string.IsNullOrEmpty(checkpoint.StationSiCodeDeparture))
                {
                    s = s + checkpoint.StationSiCodeDeparture;
                }
            }
        }

        <tr id=" + checkpoint.Id + " data-id='" + checkpoint.Id + "' data-locked='" + checkpoint.Locked + "'>
            <td style='padding: 3px 2px 0px 0px;'>
                <a href='#' data-id='@checkpoint.Id' class='@cl selectCheckpointButton'></a>&nbsp;
                @checkpoint.Name
            </td>
            @* Izpis kode *@
            <td>
                @(new HtmlString(s))
            </td>
            @* Premik gor/dol *@
            <td>@if (!checkpoint.Locked && (Model.TrackCheckpoints.First() != checkpoint))
                {
                <a class="ajaxLink linkAsButton" 
                          href="@Url.Action("MoveUp", "MapTrackCheckpoint", new { id = checkpoint.Id })"
                          data-popup-name = "Urejanje kontrolne točke '<i>@checkpoint.Name</i>'"
                          data-popup-width = "500" data-popup-height = "500">&uArr;</a>
                }</td>
            <td>@if (!checkpoint.Locked && (Model.TrackCheckpoints.Last() != checkpoint))
                {
                <a class="ajaxLink linkAsButton" 
                              href="@Url.Action("MoveDown", "MapTrackCheckpoint", new { id = checkpoint.Id })"
                              data-popup-name = "Urejanje kontrolne točke '<i>@checkpoint.Name</i>'"
                              data-popup-width = "500" data-popup-height = "500">&dArr;</a>
                }</td>
            @* Ikona točke *@
            <td>
                <a  class='editStationButton @cl1 ' href="@Url.Action("Edit", "MapStation", new { id = checkpoint.StationId })" 
                    data-id='@checkpoint.StationId' 
                    title="Dvoklik za urejanje točke"></a>&nbsp; 
                @checkpoint.StationName
            </td>
            @* Točke *@
            <td>@checkpoint.Points
            </td>
            <td>
                <b>@checkpoint.TimeOptimalArrival</b>
            </td>
            @if (checkpoint.TimeForTask == "0:00:00")
            {
                <td>-
                </td>
            }
            else
            { 
                <td>
                    @checkpoint.TimeForTask
                </td>
            }
                <td>
                    @foreach (var task in checkpoint.Tasks)
                    {
                        @task.Name
                    }
                </td>
                <td>
                    @checkpoint.TimeOptimalDeparture
                </td>
            @if (checkpoint.StationIsStart)
            { 
                <td></td>
                <td>
                    <a href='@Url.Action("RemoveSpeedTrial", "Track", new { id = Model.Id })' 
                        class='ajaxLink deleteButton' 
                        title="Počisti start in cilj hitrostne etape"></a>
                </td>
                <td colspan="1"></td>
            }
            else
            { 
                <td class='error'>
                    <b>@checkpoint.TimeMaxFromStart</b>
                </td>
                var cl2 = "";
                var title2 = "";
                if (checkpoint.SpeedTrialIsStart)
                {
                    cl2 = "heStartButton";
                    title2 = "Start hitrostne etape - klik za brisanje";
                }
                else if (checkpoint.SpeedTrialIsFinish)
                {
                    cl2 = "heFinishButton";
                    title2 = "Cilj hitrostne etape - klik za brisanje";
                }
                else
                {
                    cl2 = "emptyButton";
                    title2 = "Nastavi start/cilj hitrostne etape";
                }
                <td>
                    <a href='@Url.Action("SetSpeedTrial", "Track", new { id = checkpoint.Id })' 
                        class='ajaxLink @cl2 ' 
                        title="@title2"></a>
                </td>
                <td>@checkpoint.TimeFromPrevious
                </td>
            }
            <td>
                @if (!checkpoint.Locked && !checkpoint.StationIsStart)
                { 
                    <a class="ajaxDialog linkAsButton" 
                                href="@Url.Action("EditCheckpoint", new { id = checkpoint.Id })"
                                data-popup-name = "Urejanje kontrolne točke '<i>@checkpoint.Name</i>'"
                                data-popup-width = "600" data-popup-height = "500">Uredi</a>
                  
                }
            </td>
            <td style="padding: 3px 2px 0px;">
                @if (checkpoint.Locked)
                {
                    <a class="ajaxLink lockButton" href="@Url.Action("Unlock", "MapTrackCheckpoint", new { id = checkpoint.Id })">&nbsp;</a>
                }
                else
                {
                    <a class="ajaxLink unlockButton" href="@Url.Action("Lock", "MapTrackCheckpoint", new { id = checkpoint.Id })">&nbsp;</a>
                }
            </td>
            <td>
                @if (!checkpoint.Locked)
                {
                    <a href='@Url.Action("Delete", "MapTrackCheckpoint", new { id = checkpoint.Id })' 
                        class='ajaxLink deleteButton' 
                        title="Odstrani točko"></a>
                }
            </td>
        </tr> 
    }
</table>

src/Mrtn.Marvin21.Ui.Mvc/Views/TrackManual/_Tracks.cshtml
@model System.Collections.Generic.List<Mrtn.Marvin21.Model.Tracks.TrackViewModel>
@using System.Web.Management
@using Mrtn.Marvin21.Model.Teams
@using Mrtn.Marvin21.Ui.Mvc.Extenders
<table class="standard-table">
    <tr>
        <th>Kat.
        </th>
        @{foreach (int day in ViewBag.Days)
          {
            <th colspan="4" style="width: 50%;">Dan @day
            </th>
          }
        }
    </tr>
    @foreach (CategoryViewModel cat in ViewBag.Categories)
    {
        <tr>
            <td>@cat.Abbr</td>
            @{foreach (int day in ViewBag.Days)
              {
                  var track = Model.FirstOrDefault(x => x.Day == day && x.CategoryAbbr == cat.Abbr);
                  if (track == null)
                  {
                <td colspan="4">@( Html.ActionLink("Dodaj progo", "AddTrack", new { category = cat.Id, day = day }, new
                        {
                            @class = "ajaxLink linkAsButton ",
                            data_question = String.Format("Ali naj ustvarim progo kategorijo {0} za dan {1}?", cat.Name, day)
                        }))
                </td>
                  }
                  else
                  {
                <td data-id="@track.Id">Kategorija <b>@track.CategoryAbbr, @track.Day dan</b>
                </td>
                <td data-id="@track.Id">Čas na progi: <b>@track.OptimalPathTime</b>
                </td>
                <td data-id="@track.Id">Čas z nalogami: <b>@track.OptimalTime</b>
                </td>
                <td data-id="@track.Id">KT-jev: <b>@track.TrackCheckpointsCount</b>
                </td>

                  }
              }
            }


        </tr>
    }
</table>