src/Mrtn.Marvin21.Ui.Mvc/Controllers/SiChipController.cs
using System;
using System.Web.Mvc;
using Mrtn.Marvin21.Bl.Interface.Si;
using Mrtn.Marvin21.Bl.Services.Si;
using Mrtn.Marvin21.Model.Si;

namespace Mrtn.Marvin21.Ui.Mvc.Controllers
{
    public class SiChipController : Controller
    {

        readonly ISiChipService _siChipService = new SiChipService();
        
        /// <summary>
        ///  Vrne "okvir" za Index in potem takoj naloži tabelo
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetSiChips()
        {
            var queryModel = new SiChipQueryModel { };
            var model = _siChipService.Get(queryModel);
            return PartialView("_List", model);
        }
        [HttpGet]
        public ActionResult Edit(int? id)
        {
            try
            {
                var model = _siChipService.Edit(id);
                return PartialView("_Edit", model);
            }
            catch (Exception ee)
            {
                return PartialView("exception", ee);
            }
        }


        [HttpPost]
        public JsonResult Edit(SiChipEditModel model)
        {
            var response = _siChipService.Save(model);
            return Json(response, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult AddPacket(bool @private)
        {
            return PartialView("_AddPacket", @private);
        }
        [HttpPost]
        public ActionResult AddPacket(bool @private, string siCodes)
        {
            var response = _siChipService.AddPacket(siCodes, @private);
            return Json(response, JsonRequestBehavior.AllowGet);
        }

        public JsonResult Delete(int id)
        {
            var response = _siChipService.Delete(id);
            return Json(response, JsonRequestBehavior.AllowGet);
        }

        public JsonResult Deactivate(int id)
        {
            var response = _siChipService.Deactivate(id);
            return Json(response, JsonRequestBehavior.AllowGet);
        }
        public JsonResult Activate(int id)
        {
            var response = _siChipService.Activate(id);
            return Json(response, JsonRequestBehavior.AllowGet);
        }



    }
}

src/Mrtn.Marvin21.Ui.Mvc/Controllers/TeamController.cs
using System;
using System.Web.Mvc;
using Mrtn.Marvin21.Bl.Interface.Teams;
using Mrtn.Marvin21.Bl.Services.Teams;
using Mrtn.Marvin21.Model.Common;
using Mrtn.Marvin21.Model.Teams;

namespace Mrtn.Marvin21.Ui.Mvc.Controllers
{
    public class TeamController : Controller
    {

        readonly ITeamService _teamService = new TeamService();

        public ActionResult Index(TeamQueryModel queryModel)
        {
            if (queryModel == null) queryModel = new TeamQueryModel();
            ViewBag.DataForFilters = _teamService.GetDataForFilters();
            return View(queryModel);
        }
        public ActionResult GetTeams(TeamQueryModel queryModel)
        {
            if (queryModel == null) queryModel = new TeamQueryModel();
            queryModel.ShowInactive = GetShowInactiveTeamFromSession();
            var model = _teamService.Get(queryModel);
            ViewBag.InactiveCount = _teamService.GetInactiveTeamsCount();
            ViewBag.ShowInactive = GetShowInactiveTeamFromSession();
            return PartialView("_List", model);
        }


        [HttpGet]
        public ActionResult Edit(int? id)
        {
            try
            {
                var model = _teamService.Edit(id);
                return PartialView("_Edit", model);
            }
            catch (Exception ee)
            {
                return PartialView("exception", ee);
            }
        }

        [HttpPost]
        public JsonResult Edit(TeamEditModel model)
        {
            var response = _teamService.Save(model);
            return Json(response, JsonRequestBehavior.AllowGet);
        }

        public JsonResult Deactivate(int id)
        {
            var response = _teamService.Deactivate(id);
            return Json(response, JsonRequestBehavior.AllowGet);
        }
        public JsonResult Activate(int id)
        {
            var response = _teamService.Activate(id);
            return Json(response, JsonRequestBehavior.AllowGet);
        }

        public JsonResult ShowInactive(bool show)
        {
            Session["ShowInactiveTeams"] = show;
            return Json(new SuccessResponse { Ok = true }, JsonRequestBehavior.AllowGet);
        }

        /*
        public ActionResult GetCategories(bool active)
        {
            var queryModel = new PackQueryModel { Active = active };
            var model = _teamService.Get(queryModel);
            if (active) return PartialView("_IndexActive", model);
            return PartialView("_IndexInactive", model);
        }


*/

        private bool GetShowInactiveTeamFromSession()
        {

            if (Session["ShowInactiveTeams"] == null)
                Session["ShowInactiveTeams"] = true;
            return (bool)Session["ShowInactiveTeams"];
        }

    }

}

src/Mrtn.Marvin21.Ui.Mvc/Controllers/TeamSpreadsheetController.cs
using System;
using System.Web.Mvc;
using Mrtn.Marvin21.Bl.Interface.Teams;
using Mrtn.Marvin21.Bl.Services.Teams;
using Mrtn.Marvin21.Model.Common;
using Mrtn.Marvin21.Model.Teams;

namespace Mrtn.Marvin21.Ui.Mvc.Controllers
{
    public class TeamSpreadsheetController : Controller
    {

        readonly ITeamService _teamService = new TeamService();
        //
        // GET: /TeamSperadsheet/

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult EditSpreadsheet()
        {
            var queryModel = new TeamQueryModel { ShowInactive = GetShowInactiveTeamFromSession() };
            var model = _teamService.Get(queryModel);
            ViewBag.InactiveCount = _teamService.GetInactiveTeamsCount();
            ViewBag.ShowInactive = GetShowInactiveTeamFromSession();
            return PartialView("_Spreadsheet", model);
        }

        public JsonResult TrySaveCell(int id, string no, string siCode)
        {
            try
            {
                var response= new SuccessResponse(false,"Nobena lastnost ni bila nastavljena");
                if (siCode != null)
                {
                    response = _teamService.SetSiCode(id, siCode);
                }
                if (no != null)
                {
                    int? intNo = null;
                    no = no.Trim();
                    if (no != "")
                    {
                        int i;
                        if (Int32.TryParse(no, out i))
                            intNo = i;
                        else
                            return Json(new SuccessResponse { Ok = false, Message = "Vnesti je potrebno številko" }, JsonRequestBehavior.AllowGet);
                    }
                    response = _teamService.SetNo(id, intNo);
                }
                return Json(response, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ee)
            {
                return Json(new SuccessResponse
                {
                    Ok = false,
                    Message = ee.Message
                }, JsonRequestBehavior.AllowGet);
            }
        }

        private bool GetShowInactiveTeamFromSession()
        {

            if (Session["ShowInactiveTeams"] == null)
                Session["ShowInactiveTeams"] = true;
            return (bool)Session["ShowInactiveTeams"];
        }
    }
}

src/Mrtn.Marvin21.Ui.Mvc/Views/TeamSpreadsheet/Index.cshtml
@{
    ViewBag.Title = "Urejanje ekip po žrebanju";
}
<div  id="topMeni" style="float:right">
    <p>
        @Html.ActionLink("Seznam ekip", "Index", "Team", null, new { @class = "linkAsButton" })
        @Html.ActionLink("SI čipi", "Index", "SiChip", null, new { @class = "linkAsButton" })
        @Html.ActionLink("Osveži seznam", "Index", "TeamSpreadsheet", null, new { @class = "linkAsButton" })
    </p>
</div>
<h2>
    Seznam ekip</h2>
<div id="Teams">
</div>
<script type="text/javascript">
    var refreshTeams = function () {
        $.get('@Url.Action("EditSpreadsheet", new { })?' + new Date().getTime(),
            function (data) {
                $("#Teams").html(data);
            }
        );
    }
    $(function () {
        // Handler for .ready() called.
        refreshTeams();
    });
</script>

src/Mrtn.Marvin21.Ui.Mvc/Views/TeamSpreadsheet/_Spreadsheet.cshtml
@model List<Mrtn.Marvin21.Model.Teams.TeamViewModel>
<table class="standard-table" style="border-bottom: solid 2px #5c87b2;">
    <tr>
        <th>
            Ekipa
        </th>
        <th>
            Št. ekipe
        </th>
        <th>
            Št. čipa
        </th>
        <th>
            Privat čip
        </th>
        <th>
            Rod
        </th>
        <th>
            Kategorija
        </th>
        <th>
            Aktivna
        </th>
        <th>
            Konkurenca
        </th>
    </tr>
    @{var i = 0;}
    @{var previousCategoryId = 0;}
    @foreach (var item in Model)
    {
        i++;
        if (item.CategoryId != previousCategoryId)
        {
            previousCategoryId = item.CategoryId;
        <tr>
            <td colspan="8" style="border-top: solid 2px #5c87b2;">
                <b>
                    @item.CategoryName</b>
            </td>
        </tr>
        }
        <tr>
            <td>
                @item.Name
            </td>
            <td>
                <input type="text" value="@item.No" name="no" id="no-@item.Id"
                class="spreadsheetCell" maxlength="3" style="width:50px; text-align:right;"
                data-row="@i" data-col="1" data-id="@item.Id" />
            </td>
            <td>
                <input type="text" value="@item.SiCode" name="siCode" id="siCode-@item.Id"
                class="spreadsheetCell @(String.IsNullOrWhiteSpace(item.SiCodeError) ? "" : "warningValue")"
                maxlength="7" style="width:80px; text-align:right;"
                data-row="@i" data-col="2" data-id="@item.Id"
                data-error-message="@item.SiCodeError" />
            </td>
            <td>
                @item.PrivateSiCode
            </td>
            <td>
                @item.PackName
            </td>
            <td>
                @item.CategoryName
            </td>
            <td>
                @(item.Active ? "DA" : "NE")
            </td>
            <td>
                @(item.InCompetition ? "DA" : "-")
            </td>
        </tr>
    }
</table>
<div id="statusLine">
</div>
<script type="text/javascript">
    //
    // function selectDuplicates(<št stolpca>)
    // 
    // Ta funkcija preveri, ali so v določenem stolpcu vrednosti podvojene.
    // Celice, ki spadajo v isti stolpec, prepozna po kriteriju
    //     input:text.spreadsheetCell[data-col=<št stolpca>]
    //
    // Podvojene označi s classom duplicatedValue. 
    // Prav tako jim nastavi vrednost atributa "data-duplicate-message"
    //
    var selectDuplicates = function (col) {
        //console.debug("selectDuplicates(" + col + ")");
        $("input:text.spreadsheetCell[data-col='" + col + "']input:text.spreadsheetCell[data-col='" + col + "']")
            .removeClass("duplicatedValue")
            .data("duplicate-message","")
            .each(function (index, element) {
                if ($(this).val() != "") { 
                    var selCells = $("input:text.spreadsheetCell[data-col='" + col + "'][value='" + $(this).val() + "']");
                    if (selCells.length > 1) {
                        selCells
                            .addClass("duplicatedValue")
                            .data("duplicate-message","Vrednost celice je podvojena!");
                    } 
                }
            });
    }

    //
    // function tryStoreCell(url, cell)
    // 
    // Ta funkcija poskusi shranit podano celico. Zanaša se na to, da ima celica dva dodatna podatka:
    //  - data-name: Ime polja
    //  - data-id: Id vrstice oz entitete
    //  - data-value: Stara vrednost polja, ta se vrne v celico, če je shranjevanje neuspešno.
    // 
    // Shranjevanje se izvede tako, da funkcija pokliče podani URL na naslednji način:
    //    <url>?<data-name>=<vrednost>&id=<data-id>
    // 
    // Kot odgovor se pričakuje json s strukturo
    //  - data.Ok (boolean)
    //  - data.Message (string), če je OK je warning, sicer error message
    // 
    // Če je shranjevanje neuspešno vrne v celico prejšnjo vrednost in focus na celico
    // Če smo dobili message različen od "", celica dobi class "warningValue". 
    // V vsakem primeru se nastavi "data-error-message"
    //
    var tryStoreCell = function(url, cell){
        //console.debug("tryStoreCell(" + url + ",cell) , cellname=" + cell.attr("name") );
        $.get(url + "?" + $(cell).attr("name") + "=" + $(cell).val() + "&id=" + $(cell).data("id") ,
                function (data) {
                    $(cell).data("error-message",data.Message).removeClass("warningValue");
                    if (!data.Ok) 
                        $(cell)
                            .val($(cell).data("value"))
                            .focus();
                    if(data.Message && data.Message!="")  $(cell).addClass("warningValue")
                    selectDuplicates($(cell).data("col"));
                }
            );
    };

    //
    // function showCellMessage(cell)
    //
    // Ta funkcija v statusni vrstici pokaže sporočilo, shranjeno za podano celico.
    // Sporočila se nahajajo v naslednjih dveh atributih:
    //   - data-error-message (nastavlja ga funkcija tryStoreCell)
    //   - data-duplicate-message  (nsatavlja ga funkcija selectDuplicates)
    //
    // Prikaz poteka takole:
    // 1: če obstaja data-error-message, pokaže tega, sicer
    // 2: če obstaja data-duplicate-message, pokaže tega, sicer
    // 3: izbriše vsebino statusne vrstice
    //
    var showCellMessage = function(cell){
        //console.debug("err:'" + cell.data("error-message") + "', dup:'" + cell.data("duplicate-message")+"'");
        if(cell.data("error-message") && cell.data("error-message") !="")
            $("#statusLine").html(cell.data("error-message"));
        else if(cell.data("duplicate-message") && cell.data("duplicate-message")!="")
            $("#statusLine").html(cell.data("duplicate-message"));
        else 
            $("#statusLine").html("");
    }

    
    //
    // Definicija handler funkcij za dogodke na poljih celic
    // 
    var handlers=new Object();
    // focusHandler (onGotFocus): 
    // - shrani obstoječo vrednost v atribut data-value
    // - prikaže sporočila za to celico v statusni vrstici
    // - izbere vse v celici 
    handlers.focusHandler= function () {
        $(this).data("value", $(this).val());
        showCellMessage($(this));
        // Select input field contents
        this.select();
    }
    // keyDown, proži premike po celicah
    handlers.keyDownHandler=function(event) {
        if (event.which == 13) {
            event.preventDefault();
        }
        if (event.which > 36 && event.which < 41) {
            // arrow key has beeen pressed
            var row = $(this).data("row");
            var col = $(this).data("col");
            if (event.which == 38) row--; //up
            if (event.which == 40) row++; //down
            if (event.which == 37) col--; //left
            if (event.which == 39) col++; //down
            event.preventDefault();
            $("input:text.spreadsheetCell[data-row='" + row + "'][data-col='" + col + "']").focus();
        }
    }
    //  blurHandler (onCellLeave): Proži shranjevanje, če je bila vsebina spremenjena
    handlers.blurHandler=function () {
        if ($(this).val() != $(this).data("value")) 
            tryStoreCell("@Url.Action("TrySaveCell")", $(this));
    }
    //********************************
    //
    // Document.ready funkcija
    //
    //********************************
    $(function () {
        // aktivacija "spreadsheeta"
        $("input:text.spreadsheetCell")
            .keydown(handlers.keyDownHandler)
            .focus(handlers.focusHandler)
            .blur(handlers.blurHandler);
        // primerno označevanje podvojenih
        selectDuplicates(1);
        selectDuplicates(2);
        // skok na prvo celico
        $("input:text:visible:first").focus();
    })
</script>