src/Mrtn.Marvin21.Ui.Mvc/Controllers/HomeController.cs
using System.Web.Mvc;

namespace Mrtn.Marvin21.Ui.Mvc.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View("IndexHome");
        }

        public ActionResult About()
        {
            return View();
        }
    }
}

src/Mrtn.Marvin21.Ui.Mvc/Controllers/PackController.cs
using System;
using System.Web.Mvc;
using Mrtn.Marvin21.Bl.Interface.Teams;
using Mrtn.Marvin21.Bl.Services.Teams;
using Mrtn.Marvin21.Model.Teams;

namespace Mrtn.Marvin21.Ui.Mvc.Controllers
{
    public class PackController : Controller
    {

        readonly IPackService _packService = new PackService();


        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Edit(int? id)
        {
            try
            {
                var model = _packService.Edit(id);
                return PartialView("_Edit", model);
            }
            catch (Exception ee)
            {
                return PartialView("exception", ee);
            }
        }

        [HttpPost]
        public JsonResult Edit(PackEditModel model)
        {
            var response = _packService.Save(model);
            return Json(response, JsonRequestBehavior.AllowGet);

        }

        public ActionResult GetCategories(bool active)
        {
            var queryModel = new PackQueryModel { Active = active };
            var model = _packService.Get(queryModel);
            if (active) return PartialView("_ListActive", model);
            return PartialView("_ListInactive", model);
        }

        public JsonResult Deactivate(int id)
        {
            var response = _packService.Deactivate(id);
            return Json(response, JsonRequestBehavior.AllowGet);
        }
        public JsonResult Activate(int id)
        {
            var response = _packService.Activate(id);
            return Json(response, JsonRequestBehavior.AllowGet);
        }
    }

}

src/Mrtn.Marvin21.Ui.Mvc/Controllers/TaskController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Mrtn.Marvin21.Model.Teams;
using Mrtn.Marvin21.Bl.Interface.Tasks;
using Mrtn.Marvin21.Bl.Interface.Teams;
using Mrtn.Marvin21.Bl.Services.Tasks;
using Mrtn.Marvin21.Bl.Services.Teams;
using Mrtn.Marvin21.Model.Tasks;

namespace Mrtn.Marvin21.Ui.Mvc.Controllers
{
    public class TaskController : Controller
    {

        readonly ITaskService _taskService = new TaskService();
        readonly ICategoryService _categoryService = new CategoryService();


        public ActionResult Index(int? id)
        {
            ViewBag.Id = id.GetValueOrDefault();
            return View();
        }

        public ActionResult GetTasks()
        {
            var model = _taskService.Get();
            ViewBag.Categories = _categoryService.GetAll();
            return PartialView("_List", model);
        }

        [HttpGet]
        public ActionResult Edit(int? id)
        {
            try
            {
                var model = _taskService.Edit(id);

                return PartialView("_Edit", model);
            }
            catch (Exception ee)
            {
                return PartialView("exception", ee);
            }
        }

        [HttpPost]
        public JsonResult Edit(TaskEditModel model, bool? useSecondEntry, string location)
        {
            if(useSecondEntry==null ||useSecondEntry.Value==false)
            {
                model.SecondEntryName = "";
            }
            if(location=="BeforeStart")
            {
                model.BeforeStart = true;
                model.OnTrack = false;
                model.AfterFinish = false;
                model.StationId = 0;
            }
            else if (location == "AfterFinish")
            {
                model.BeforeStart = false;
                model.OnTrack = false;
                model.AfterFinish = true;
                model.StationId = 0;
            }
            else
            {
                model.BeforeStart = false;
                model.OnTrack = true;
                model.AfterFinish = false;
            }

            var response = _taskService.Save(model);
            return Json(response, JsonRequestBehavior.AllowGet);
        }

        public JsonResult Lock(int id)
        {
            var response = _taskService.Lock(id);
            return Json(response, JsonRequestBehavior.AllowGet);
        }

        public JsonResult Unlock(int id)
        {
            var response = _taskService.Unlock(id);
            return Json(response, JsonRequestBehavior.AllowGet);
        }



    }
}

src/Mrtn.Marvin21.Ui.Mvc/Controllers/TeamController.cs
using System;
using System.Web.Mvc;
using Mrtn.Marvin21.Bl.Interface.Teams;
using Mrtn.Marvin21.Bl.Services.Teams;
using Mrtn.Marvin21.Model.Common;
using Mrtn.Marvin21.Model.Teams;

namespace Mrtn.Marvin21.Ui.Mvc.Controllers
{
    public class TeamController : Controller
    {

        readonly ITeamService _teamService = new TeamService();

        public ActionResult Index(TeamQueryModel queryModel)
        {
            if (queryModel == null) queryModel = new TeamQueryModel();
            ViewBag.DataForFilters = _teamService.GetDataForFilters();
            return View(queryModel);
        }
        public ActionResult GetTeams(TeamQueryModel queryModel)
        {
            if (queryModel == null) queryModel = new TeamQueryModel();
            queryModel.ShowInactive = GetShowInactiveTeamFromSession();
            var model = _teamService.Get(queryModel);
            ViewBag.InactiveCount = _teamService.GetInactiveTeamsCount();
            ViewBag.ShowInactive = GetShowInactiveTeamFromSession();
            return PartialView("_List", model);
        }


        [HttpGet]
        public ActionResult Edit(int? id)
        {
            try
            {
                var model = _teamService.Edit(id);
                return PartialView("_Edit", model);
            }
            catch (Exception ee)
            {
                return PartialView("exception", ee);
            }
        }

        [HttpPost]
        public JsonResult Edit(TeamEditModel model)
        {
            var response = _teamService.Save(model);
            return Json(response, JsonRequestBehavior.AllowGet);
        }

        public JsonResult Deactivate(int id)
        {
            var response = _teamService.Deactivate(id);
            return Json(response, JsonRequestBehavior.AllowGet);
        }
        public JsonResult Activate(int id)
        {
            var response = _teamService.Activate(id);
            return Json(response, JsonRequestBehavior.AllowGet);
        }

        public JsonResult ShowInactive(bool show)
        {
            Session["ShowInactiveTeams"] = show;
            return Json(new SuccessResponse { Ok = true }, JsonRequestBehavior.AllowGet);
        }

        /*
        public ActionResult GetCategories(bool active)
        {
            var queryModel = new PackQueryModel { Active = active };
            var model = _teamService.Get(queryModel);
            if (active) return PartialView("_IndexActive", model);
            return PartialView("_IndexInactive", model);
        }


*/

        private bool GetShowInactiveTeamFromSession()
        {

            if (Session["ShowInactiveTeams"] == null)
                Session["ShowInactiveTeams"] = true;
            return (bool)Session["ShowInactiveTeams"];
        }

    }

}

src/Mrtn.Marvin21.Ui.Mvc/Controllers/TrackController.cs
using System.Web.Mvc;
using Mrtn.Marvin21.Bl.Interface.Tracks;
using Mrtn.Marvin21.Bl.Services.Tracks;
using Mrtn.Marvin21.Model.Tracks;

namespace Mrtn.Marvin21.Ui.Mvc.Controllers
{
    public class TrackController : Controller
    {
        readonly ITrackService _trackService = new TrackService();

        public ActionResult Index(int? id)
        {
            ViewBag.Id = id.GetValueOrDefault();
            return View();
        }


        public ActionResult GetTracks(TrackQueryModel queryModel)
        {
            if (queryModel == null) queryModel = new TrackQueryModel();
            var model = _trackService.GetTracks(queryModel);
            return PartialView("_List", model);
        }

        public ActionResult GetTrack(int id)
        {
            if (id == 0) return Content("Izberi progo");
            var model = _trackService.Get(id);
            return PartialView("_Track", model);
        }

        //[HttpGet]
        //public ActionResult Edit(int? id)
        //{
        //    try
        //    {
        //        var model = _trackService.Edit(id);
        //        return PartialView("_Edit", model);
        //    }
        //    catch (Exception ee)
        //    {
        //        return PartialView("exception", ee);
        //    }
        //}

        //[HttpPost]
        //public JsonResult Edit(TrackEditModel model)
        //{
        //    var response = _trackService.Save(model);
        //    return Json(response, JsonRequestBehavior.AllowGet);
        //}



        public JsonResult RemoveSpeedTrial(int id)
        {
            //id=idTrack
            var response = _trackService.RemoveSpeedTrial(id);
            return Json(response, JsonRequestBehavior.AllowGet);
        }

        public JsonResult SetSpeedTrial(int id)
        {
            //id = idCheckpoint
            var response = _trackService.SetSpeedTrial(id);
            return Json(response, JsonRequestBehavior.AllowGet);
        }

        public JsonResult Lock(int id)
        {
            var response = _trackService.Lock(id);
            return Json(response, JsonRequestBehavior.AllowGet);
        }
        public JsonResult Unlock(int id)
        {
            var response = _trackService.Unlock(id);
            return Json(response, JsonRequestBehavior.AllowGet);
        }

    }
}

src/Mrtn.Marvin21.Ui.Mvc/Views/Home/About.cshtml
@{
    ViewBag.Title = "About Us";
}

<h2>About</h2>
<p>
     Put content here.
</p>

src/Mrtn.Marvin21.Ui.Mvc/Views/Home/IndexHome.cshtml
@{
    ViewBag.Title = "Marvin";
}
<style>
    /* skupne lastnosi */
    div.box
    {
        position: absolute;
        padding-top: 20px;
        padding-bottom: 20px;
        height: 20px;
        width: 200px;
        border-radius: 5px;
        background-color: #e8eef4;
        border: solid 1px #5c87b2;
        font-family: Arial, Helvetica, sans-serif;
        font-size: 16px;
        text-align: center;
        vertical-align: middle;
        cursor: pointer;
    }
    div.box:hover
    {
        background-color: #5c87b2;
        color: White;
    }
</style>
<div style="position: relative; height: 600px;" id="container">
    <div id="categories" class="box" style="top: 220px; left: 0px;">
        Tekmovalne kategorije</div>
    <div id="packs" class="box" style="top: 0px; left: 0px;">
        Rodovi</div>
    <div id="teams" class="box" style="top: 110px; left: 0px;">
        Ekipe</div>
    <div id="siChips" class="box" style="top: 0px; left: 250px;">
        SI čipi</div>
    <div id="teamSpreadsheet" class="box" style="top: 110px; left: 250px;">
        Po žrebanju ekip</div>
    <div id="stationsOnMap" class="box" style="top: 0px; left: 500px;">
        Točke na zemljevidu</div>
    <div id="stations" class="box" style="top: 0px; left: 700px;">
        Točke </div>
    <div id="paths" class="box" style="top: 110px; left: 500px;">
        Poti med točkami</div>
    <div id="tracksOnMap" class="box" style="top: 220px; left: 500px;">
        Proge na zemljevidu</div>
    <div id="tracksManual" class="box" style="top: 220px; left: 700px;">
        Ročni vnos prog</div>
    <div id="tracks" class="box" style="top: 330px; left: 500px;">
        Proge</div>
    <div id="tasks" class="box" style="top: 0px; left: 1000px;">
        Naloge</div>
    <div id="dashboard" class="box" style="top: 220px; left: 1000px;">
        Nadzorna plošča</div>
</div>
<script type="text/javascript">
    $(function () {
        $("#categories")
        .click(function () {
            window.location = '@Url.Action("Index", "Category")';
        });
        $("#packs")
        .click(function () {
            window.location = '@Url.Action("Index", "Pack")';
        });
        $("#teams")
        .click(function () {
            window.location = '@Url.Action("Index", "Team")';
        });
        $("#siChips")
        .click(function () {
            window.location = '@Url.Action("Index", "SiChip")';
        });
        $("#teamSpreadsheet")
        .click(function () {
            window.location = '@Url.Action("Index", "TeamSpreadsheet")';
        });
        $("#stationsOnMap")
        .click(function () {
            window.location = '@Url.Action("Index", "MapStation")';
        });
        $("#stations")
        .click(function () {
            window.location = '@Url.Action("Index", "Station")';
        });
        $("#paths")
        .click(function () {
            window.location = '@Url.Action("Index", "MapPath")';
        });
        $("#tracksOnMap")
        .click(function () {
            window.location = '@Url.Action("Index", "MapTrack")';
        });
        $("#tracksManual")
        .click(function () {
            window.location = '@Url.Action("Index", "TrackManual")';
        });
        $("#tracks")
        .click(function () {
            window.location = '@Url.Action("Index", "Track")';
        });
        $("#tasks")
        .click(function () {
            window.location = '@Url.Action("Index", "Task")';
        });
        $("#dashboard")
        .click(function () {
            window.location = '@Url.Action("Index", "Dashboard")';
        }); //Rodovi --> Ekipe
        _drawLine({
            x1: 100,
            y1: 60,
            x2: 100,
            y2: 110,
            color: "#777777",
            width: 2,
            zorder: 100,
            class: "",
            arrows: ["5%"],
            relative: false
        }, $("#container"));

        //Kategorije --> Ekipe
        _drawLine({
            x1: 100,
            y1: 220,
            x2: 100,
            y2: 170,
            color: "#777777",
            width: 2,
            zorder: 100,
            class: "",
            arrows: ["5%"],
            relative: false
        }, $("#container"));

        //  SiČipi --> Po žrebanju
        _drawLine({
            x1: 350,
            y1: 60,
            x2: 350,
            y2: 110,
            color: "#777777",
            width: 2,
            zorder: 100,
            class: "",
            arrows: ["5%"],
            relative: false
        }, $("#container"));

        //  ekipe --> Po žrebanju
        _drawLine({
            x1: 200,
            y1: 140,
            x2: 250,
            y2: 140,
            color: "#777777",
            width: 2,
            zorder: 100,
            class: "",
            arrows: ["5%"],
            relative: false
        }, $("#container"));

        //točke --> Poti
        _drawLine({
            x1: 600,
            y1: 60,
            x2: 600,
            y2: 110,
            color: "#777777",
            width: 2,
            zorder: 100,
            class: "",
            arrows: ["5%"],
            relative: false
        }, $("#container"));
        //poti --> proge na zemljevidu
        _drawLine({
            x1: 600,
            y1: 170,
            x2: 600,
            y2: 220,
            color: "#777777",
            width: 2,
            zorder: 100,
            class: "",
            arrows: ["5%"],
            relative: false
        }, $("#container"));

        // kategorije --> proge na zemljevidu
        _drawLine({
            x1: 200,
            y1: 250,
            x2: 500,
            y2: 250,
            color: "#777777",
            width: 2,
            zorder: 100,
            class: "",
            arrows: ["2%"],
            relative: false
        }, $("#container"));

        //proge na zemljevidu --> proge 
        _drawLine({
            x1: 600,
            y1: 280,
            x2: 600,
            y2: 330,
            color: "#777777",
            width: 2,
            zorder: 100,
            class: "",
            arrows: ["5%"],
            relative: false
        }, $("#container"));




    })


</script>